name: dotnet package

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - '**/.gitignore'
      - '**/README.md'
      
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          source-url: https://nuget.pkg.github.com/jeffu231/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Display dotnet version
        run: dotnet --version
      - name: Install Dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build -c Release --no-restore
      - name: Create the Flexlib package
        run: dotnet pack -c Release FlexLib
      - name: Publish the Flexlib package to GPR
        run: dotnet nuget push --skip-duplicate FlexLib/bin/Release/*.nupkg
      - name: Create the Util package
        run: dotnet pack -c Release Util
      - name: Publish the Util package to GPR
        run: dotnet nuget push --skip-duplicate Util/bin/Release/*.nupkg
      - name: Create the Vita package
        run: dotnet pack -c Release Vita
      - name: Publish the Vita package to GPR
        run: dotnet nuget push --skip-duplicate Vita/bin/Release/*.nupkg
      - name: Create the UiWpfFramework package
        run: dotnet pack -c Release UiWpfFramework
      - name: Publish the UiWpfFramework package to GPR
        run: dotnet nuget push --skip-duplicate UiWpfFramework/bin/Release/*.nupkg
